# Cloud Build configuration for Google Cloud Run deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sonic-467415/sonic-api:$COMMIT_SHA', '.']
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sonic-467415/sonic-api:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sonic-api'
      - '--image=gcr.io/sonic-467415/sonic-api:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=ASPNETCORE_ENVIRONMENT=Production'
      - '--set-secrets=SONIC_AUTH_DB_CONNECTION_STRING=SONIC_AUTH_DB_CONNECTION_STRING:latest'
      - '--set-secrets=TOKEN=TOKEN:latest'
      - '--set-secrets=GOOGLEAUTH_CLIENT_ID=GOOGLEAUTH_CLIENT_ID:latest'
      - '--set-secrets=GOOGLEAUTH_CLIENT_SECRET=GOOGLEAUTH_CLIENT_SECRET:latest'
      - '--set-secrets=SPOTIFY_CLIENT_ID=SPOTIFY_CLIENT_ID:latest'
      - '--set-secrets=SPOTIFY_CLIENT_SECRET=SPOTIFY_CLIENT_SECRET:latest'
      - '--set-secrets=SPOTIFY_TOKEN_URL=SPOTIFY_TOKEN_URL:latest'
      - '--set-secrets=ISSUER=ISSUER:latest'
      - '--set-secrets=AUDIENCE=AUDIENCE:latest'
      - '--set-secrets=GOOGLE_MAPS_API_KEY=GOOGLE_MAPS_API_KEY:latest'
      - '--set-secrets=GOOGLE_FIELDMASK_PLACE_AUTOCOMPLETE=GOOGLE_FIELDMASK_PLACE_AUTOCOMPLETE:latest'
      - '--set-secrets=GOOGLE_FIELDMASK_PLACE_DETAILS=GOOGLE_FIELDMASK_PLACE_DETAILS:latest'
      - '--add-cloudsql-instances=sonic-467415:us-central1:sonic-postgres'

# Specify the machine type for Cloud Build
options:
  machineType: 'E2_HIGHCPU_8'

# Store images in Container Registry
images:
  - 'gcr.io/sonic-467415/sonic-api:$COMMIT_SHA'
