# Cloud Build configuration for Google Cloud Run deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/sonic-467415/sonic-api/sonic-api:$COMMIT_SHA', '.']
  
  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/sonic-467415/sonic-api/sonic-api:$COMMIT_SHA']

  # Build migration image with EF tools and Cloud SQL proxy
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'migration-runner', '-f', 'Dockerfile.migrations', '.']

  # Run migrations using our custom migration image with secret
  - name: 'migration-runner'
    secretEnv: ['SONIC_AUTH_DB_CONNECTION_STRING']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sonic-api'
      - '--image=us-central1-docker.pkg.dev/sonic-467415/sonic-api/sonic-api:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=ASPNETCORE_ENVIRONMENT=Production'
      - '--set-secrets=SONIC_AUTH_DB_CONNECTION_STRING=SONIC_AUTH_DB_CONNECTION_STRING:latest'
      - '--set-secrets=TOKEN=TOKEN:latest'
      - '--set-secrets=GOOGLEAUTH_CLIENT_ID=GOOGLEAUTH_CLIENT_ID:latest'
      - '--set-secrets=GOOGLEAUTH_CLIENT_SECRET=GOOGLEAUTH_CLIENT_SECRET:latest'
      - '--set-secrets=SPOTIFY_CLIENT_ID=SPOTIFY_CLIENT_ID:latest'
      - '--set-secrets=SPOTIFY_CLIENT_SECRET=SPOTIFY_CLIENT_SECRET:latest'
      - '--set-secrets=SPOTIFY_TOKEN_URL=SPOTIFY_TOKEN_URL:latest'
      - '--set-secrets=ISSUER=ISSUER:latest'
      - '--set-secrets=AUDIENCE=AUDIENCE:latest'
      - '--set-secrets=GOOGLE_MAPS_API_KEY=GOOGLE_MAPS_API_KEY:latest'
      - '--set-secrets=GOOGLE_FIELDMASK_PLACE_AUTOCOMPLETE=GOOGLE_FIELDMASK_PLACE_AUTOCOMPLETE:latest'
      - '--set-secrets=GOOGLE_FIELDMASK_PLACE_DETAILS=GOOGLE_FIELDMASK_PLACE_DETAILS:latest'
      - '--add-cloudsql-instances=sonic-467415:us-central1:sonic-postgre'

# Specify the machine type for Cloud Build
options:
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'

# Use default Cloud Build service account (recommended)
# If you need a custom service account, add:
# serviceAccount: 'projects/sonic-467415/serviceAccounts/your-service-account@sonic-467415.iam.gserviceaccount.com'

# Store images in Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/sonic-467415/sonic-api/sonic-api:$COMMIT_SHA'

# Available secrets for build steps
availableSecrets:
  secretManager:
  - versionName: projects/sonic-467415/secrets/SONIC_AUTH_DB_CONNECTION_STRING/versions/latest
    env: 'SONIC_AUTH_DB_CONNECTION_STRING'
